name: "CI"

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  ci:
    name: "CI"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs"

      - name: "Run PHP CodeSniffer"
        run: "./vendor/bin/phpcs"

      - name: "Run PHPStan"
        run: "./vendor/bin/phpstan analyse -c phpstan.neon"
